apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --out k8s
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: turbinia-server
  name: turbinia-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: turbinia-server
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --out k8s
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: turbinia-server
    spec:
      containers:
        - env:
            - name: LANG
              value: C.UTF-8
            - name: LC_ALL
              value: C.UTF-8
          image: us-docker.pkg.dev/osdfir-registry/turbinia/release/turbinia-server:latest
          name: turbinia-server
          resources: {}
          volumeMounts:
            - mountPath: /etc/turbinia/
              name: turbinia-server-conf
            - mountPath: /data
              name: evidence-pv-storage
      restartPolicy: Always
      volumes:
        - name: turbinia-server-conf
          configMap:
            name: turbinia-conf
        - name: evidence-pv-storage
          persistentVolumeClaim:
            claimName: evidence-pv-claim
status: {}
